<a href="https://colab.research.google.com/github/mukkatharun/MLBasedSpamFilter/blob/main/ML_based_spam_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
data = pd.read_csv('data.csv')
data.head()

                                             Message  Spam
0  Our records indicate your Pension is under per...  Spam
1  Enter to win $25,000 and get a Free Hotel Nigh...  Spam
2  Dear recipient,Avangar Technologies announces ...  Spam
3  I know that's an incredible statement, but bea...  Spam

In [7]:
data['Spam']=data['Spam'].map({'Spam':1})
data.head()

                                             Message  Spam
0  Our records indicate your Pension is under per...     1
1  Enter to win $25,000 and get a Free Hotel Nigh...     1
2  Dear recipient,Avangar Technologies announces ...     1
3  I know that's an incredible statement, but bea...     1

In [ ]:
msg = "Free-Coupons for next movie. The above links will take you straight to our partner's site. For more information or to see other offers available, you can also visit the Groupon on the Working Advantage website"
x_test = [msg]

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate the CountVectorizer method
count_vector = CountVectorizer(ngram_range=(1, 1), lowercase = True , stop_words =  'english')

# Fit the training data and then return the matrix
X_train = count_vector.fit_transform(data['Message'])
X_test = count_vector.transform(x_test)
X_train_feature_list = count_vector.get_feature_names()
X_train_feature_list

['000',
 '10',
 '100',
 '1500',
 '25',
 '300',
 '4000',
 '500',
 'absurd',
 'additional',
 'animals',
 'announces',
 'area',
 'articles',
 'auto',
 'avangar',
 'barnyard',
 'based',
 'bear',
 'beginning',
 'bmw',
 'book',
 'bring',
 'business',
 'businessand',
 'businesses',
 'campaign',
 'cash',
 'cats',
 'chain',
 'chance',
 'chances',
 'chocolate',
 'choice',
 'click',
 'comfortable',
 'company',
 'computer',
 'convertible',
 'cool',
 'crazy',
 'currently',
 'day',
 'dear',
 'dedicate',
 'deleted',
 'did',
 'discount',
 'dozens',
 'earn',
 'employed',
 'employment',
 'enter',
 'european',
 'expanding',
 'explain',
 'exploding',
 'extra',
 'ezventure',
 'family',
 'fast',
 'free',
 'funny',
 'gives',
 'global',
 'growth',
 'half',
 'hard',
 'helped',
 'high',
 'higher',
 'home',
 'honest',
 'hotel',
 'hours',
 'income',
 'incredible',
 'indicate',
 'internet',
 'investment',
 'inviting',
 'isn',
 'job',
 'join',
 'just',
 'know',
 'letter',
 'like',
 'looking',
 'lots',
 'low',
 'mail',
 'mainly',
 'maintenance',
 'make',
 'matically',
 'membership',
 'microsoft',
 'money',
 'nail',
 'netmarket',
 'new',
 'nice',
 'night',
 'offer',
 'offered',
 'offering',
 'offers',
 'office',
 'opportunity',
 'opt',
 'overnight',
 'pension',
 'people',
 'performing',
 'plus',
 'polish',
 'positions',
 'prize',
 'promise',
 'provides',
 'quick',
 'recipient',
 'records',
 'region',
 'regular',
 'release',
 'reply',
 'responsible',
 'review',
 'rich',
 'run',
 'runs',
 'scams',
 'schemes',
 'service',
 'shares',
 'shopping',
 'site',
 'sleep',
 'spremier',
 'started',
 'statement',
 'stock',
 'stop',
 'straightforward',
 'tech',
 'technologies',
 'theirtime',
 'time',
 'took',
 'trial',
 'trivia',
 'unprecendented',
 'vacation',
 'valuable',
 've',
 'weekly',
 'win',
 'work',
 'working',
 'worldwide',
 'years',
 'youone',
 'z3']

In [28]:
doc_array =  X_train.toarray()
test_doc_array = X_test.toarray()
doc_array

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 1,
        1, 0, 0, 0, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1,
        1, 1, 1, 3, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 3, 0, 0, 1, 0, 0]])

In [14]:
frequency_matrix = pd.DataFrame((doc_array),columns = X_train_feature_list)
frequency_matrix

   000  10  100  1500  25  300  ...  work  working  worldwide  years  youone  z3
0    0   0    0     0   1    0  ...     0        0          0      0       0   0
1    3   1    1     0   1    0  ...     0        0          0      0       0   1
2    0   0    0     1   0    1  ...     1        2          1      0       1   0
3    0   0    0     0   0    0  ...     3        0          0      1       0   0

[4 rows x 165 columns]

In [21]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
naive_bayes.fit(X_train , y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
predictions = naive_bayes.predict(X_test)
predictions

array([1])